/**
 * TypeScript interfaces for the Recipe schema
 * Defines the structure of recipe data throughout the application
 */

/**
 * Ingredient definition used in both recipe ingredients list and step ingredients
 */
export interface Ingredient {
  name: string;
  quantity: string;
  type: string;
}

/**
 * Recipe step structure defining a single instruction in the cooking process
 */
export interface RecipeStep {
  stepNumber: number;
  title: string;
  equipmentNeeded: string[];
  instructions: string;
  ingredientsUsed: Ingredient[];
  estimatedTimeMinutes: number;
  definitionOfDone: string;
}

/**
 * Metadata for categorizing and describing recipes
 */
export interface RecipeMetadata {
  cuisine: string;
  dishType: string;
  difficultyLevel: string;
}

/**
 * Complete Recipe interface with all required and optional fields
 */
export interface Recipe {
  id: string;
  title: string;
  servings: string;
  totalTimeMinutes: number;
  activeTimeMinutes: number | null;
  passiveTimeMinutes: number | null;
  metadata: RecipeMetadata;
  ingredients: Ingredient[];
  steps: RecipeStep[];
  allEquipmentNeeded: string[];
}

/**
 * Recipe input interface for creating or updating recipes
 * Omits the id field which is generated by the system
 */
export type RecipeInput = Omit<Recipe, 'id'>;

/**
 * Recipe output interface as returned by the API
 */
export type RecipeOutput = Recipe;