/**
 * Recipe Zod schema implementation for runtime validation
 * Based on the JSON Schema specifications provided in the requirements
 */
import { z } from 'zod';
import type { Recipe, RecipeInput } from '../types/recipe';

/**
 * Ingredient schema defining the structure for ingredients
 */
export const IngredientSchema = z.object({
  name: z.string().min(1, "Ingredient name is required"),
  quantity: z.string().min(1, "Quantity is required"),
  type: z.string().min(1, "Ingredient type is required"),
});

/**
 * Recipe step schema with strict validation for all required fields
 */
export const RecipeStepSchema = z.object({
  stepNumber: z.number().int().positive("Step number must be a positive integer"),
  title: z.string().min(1, "Step title is required"),
  equipmentNeeded: z.array(z.string()),
  instructions: z.string().min(1, "Instructions are required"),
  ingredientsUsed: z.array(IngredientSchema),
  estimatedTimeMinutes: z.number().int().nonnegative("Estimated time must be a non-negative integer"),
  definitionOfDone: z.string().min(1, "Definition of done is required"),
});

/**
 * Metadata schema for categorizing recipes
 */
export const RecipeMetadataSchema = z.object({
  cuisine: z.string().min(1, "Cuisine is required"),
  dishType: z.string().min(1, "Dish type is required"),
  difficultyLevel: z.string().min(1, "Difficulty level is required"),
});

/**
 * Complete Recipe schema with validation for all fields
 * Matches the JSON schema requirements exactly
 */
export const RecipeSchema = z.object({
  id: z.string().min(1, "Recipe ID is required"),
  title: z.string().min(1, "Title is required"),
  servings: z.string().min(1, "Servings information is required"),
  totalTimeMinutes: z.number().int().positive("Total time must be a positive integer"),
  activeTimeMinutes: z.number().int().nonnegative().nullable(),
  passiveTimeMinutes: z.number().int().nonnegative().nullable(),
  metadata: RecipeMetadataSchema,
  ingredients: z.array(IngredientSchema).nonempty("At least one ingredient is required"),
  steps: z.array(RecipeStepSchema).nonempty("At least one step is required"),
  allEquipmentNeeded: z.array(z.string()),
});

/**
 * Recipe input schema for creating or updating recipes
 * Omits the id field which is generated by the system
 */
export const RecipeInputSchema = RecipeSchema.omit({ id: true });

/**
 * Utility function for parsing and validating recipe input
 * @param data - The input data to validate against RecipeInputSchema
 * @returns Validated recipe input or throws validation error
 */
export function parseRecipeInput(data: unknown): RecipeInput {
  return RecipeInputSchema.parse(data);
}

/**
 * Utility function for safely parsing recipe input
 * Returns success flag and either validated data or validation errors
 * @param data - The input data to validate against RecipeInputSchema
 */
export function safeParseRecipeInput(data: unknown): { success: boolean; data?: RecipeInput; error?: z.ZodError } {
  const result = RecipeInputSchema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, error: result.error };
}

/**
 * Utility function for validating a complete recipe
 * @param data - The recipe data to validate against RecipeSchema
 * @returns Validated recipe or throws validation error
 */
export function validateRecipe(data: unknown): Recipe {
  return RecipeSchema.parse(data);
}

/**
 * Utility function for safely validating a recipe
 * Returns success flag and either validated data or validation errors
 * @param data - The recipe data to validate
 */
export function safeValidateRecipe(data: unknown): { success: boolean; data?: Recipe; error?: z.ZodError } {
  const result = RecipeSchema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, error: result.error };
}

/**
 * Type inference for TypeScript to use Zod schemas
 */
export type RecipeSchemaType = z.infer<typeof RecipeSchema>;
export type RecipeInputSchemaType = z.infer<typeof RecipeInputSchema>;